bases:
- ../../base
resources:
- quarkuscoffeeshop-barista/
- quarkuscoffeeshop-counter/
- quarkuscoffeeshop-customermocker/
- quarkuscoffeeshop-kitchen/
- quarkuscoffeeshop-inventory/
- quarkuscoffeeshop-web/