resources:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-counter
  newTag: 5.0.1-SNAPSHOT
patchesStrategicMerge:
  - patch-env.yaml