---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-app-subscription
spec:
  workspaces:
    - name: source  
  steps:
    - name: create-app-subscription
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source  
      command: ["/bin/bash", "-c"]
      args:
        - |-
          ls -lath .
          echo "**** Creating Channel and on RH ACM ****"
          oc apply -f acm-configs/02_channel.yaml -n quarkuscoffeeshop-demo
          echo "**** Creating Application Definition and on RH ACM ****"
          oc apply -f acm-configs/03_application_webapp.yaml -n quarkuscoffeeshop-demo
