---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: etherpad-dev-deployment
spec:
  workspaces:
    - name: source  
  steps:
    - name: etherpad-dev-deployment
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source  
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo "**** Creating Channel and on RH ACM ****"
          oc apply -f acm-configs/02_channel.yaml
          echo "**** Creating Application Definition and on RH ACM ****"
          oc apply -f acm-configs/03_application_webapp.yaml
