apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: quarkuscoffeshop-app     
  namespace: quarkuscoffeeshop-demo
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - quarkuscoffeshop-app
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription