apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: quarkuscoffeshop-app-cluster2
  namespace: quarkuscoffeeshop-demo
  labels:
    deployment: quarkuscoffeshop-app
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: clusters/overlays/cluster2
spec:
  channel: quarkuscoffeeshop-demo/quarkuscoffeeshop-demo-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster2