---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-customermocker
  labels:
    app: quarkuscoffeeshop-customermocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-customermocker
  template:
    metadata:
      name: quarkuscoffeeshop-customermocker-deployment
      labels:
        app:  quarkuscoffeeshop-customermocker
        app.kubernetes.io/component: quarkuscoffeeshop-customermocker
        app.kubernetes.io/instance: quarkuscoffeeshop-customermocker
        app.kubernetes.io/part-of: quarkuscoffeeshop
        quarkuscoffeeshop: ""
        app.openshift.io/runtime-namespace: quarkuscoffeeshop-demo
    spec:
      containers:
        - name: quarkuscoffeeshop-customermocker
          image: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-customermocker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REST_URL
              value: http://quarkuscoffeeshop-web-quarkuscoffeeshop-demo.apps.ocp4.example.com