apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-counter
spec:
  template:
    spec:
      containers:
        - name: quarkuscoffeeshop-counter
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: cafe-cluster-kafka-bootstrap:9092
            - name: PGSQL_URL
              value: 'jdbc:postgresql://coffeeshopdb:5432/coffeeshopdb?currentSchema=coffeeshop'
            - name: PGSQL_USER
              value: coffeshopadmin
            - name: PGSQL_PASS
              value: 'changepassword'
            - name: LOG_SQL
              value: 'true'
            - name: QUARKUS_LOG_LEVEL
              value: INFO
            - name: QUARKUSCOFFEESHOP_LOG_LEVEL
              value: DEBUG

