resources:
- quarkuscoffeeshop-barista-service.yaml
- quarkuscoffeeshop-counter-service.yaml
- quarkuscoffeeshop-customermocker-service.yaml
- quarkuscoffeeshop-kitchen-service.yaml
- quarkuscoffeeshop-web-service.yaml