---
apiVersion: v1
kind: Service
metadata:
  name: quarkuscoffeeshop-customermocker
  labels:
    app: quarkuscoffeeshop-customermocker
spec:
  selector:
    app: quarkuscoffeeshop-customermocker
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080c