resources:
- deployment.yaml
patchesStrategicMerge:
  - patch-env.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jeremydavis/quarkuscoffeeshop-barista
  newTag: 3.0.0