resources:
- deployment.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jeremydavis/quarkuscoffeeshop-web
  newTag: 3.0.0
patchesStrategicMerge:
  - patch-env.yaml
