resources:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jeremydavis/quarkuscoffeeshop-customermocker
  newTag: 4.1.0
patchesStrategicMerge:
  - patch-env.yaml