apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-barista
  labels:
    app: quarkuscoffeeshop-barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-barista
  template:
    metadata:
      name: quarkuscoffeeshop-barista-deployment
      labels:
        app:  quarkuscoffeeshop-barista
        app.kubernetes.io/component: quarkuscoffeeshop-barista
        app.kubernetes.io/instance: quarkuscoffeeshop-barista
        app.kubernetes.io/part-of: quarkuscoffeeshop
        quarkuscoffeeshop: ""
        app.openshift.io/runtime-namespace: quarkuscoffeeshop-demo
    spec:
      containers:
        - name: quarkuscoffeeshop-barista
          image: quay.io/quarkuscoffeeshop/quarkuscoffeeshop-barista:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: cafe-cluster-kafka-bootstrap:9092