apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-barista
spec:
  template:
    spec:
      containers:
        - name: quarkuscoffeeshop-barista
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: cafe-cluster-kafka-bootstrap:9092
