apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeshop-kitchen
spec:
  template:
    spec:
      containers:
        - name: quarkuscoffeshop-kitchen
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: cafe-cluster-kafka-bootstrap:9092